### ISSUE TITLE
Parsing indentation based syntax

### ISSUE THREAD

**Issue by darthdeus** [gabrielelana/paco#1]
This is more of a question than an issue. Is there a plan to specifically support parsers for indentation based syntax, such as https://hackage.haskell.org/package/indents-0.3.0/docs/Text-Parsec-Indent.html?

I'm currently looking into parser options in Elixir, since using regexps doesn't seem to be working so well for me (I'm trying to implement a http://slim-lang.com/ parser), and given that I have some experience with Parsec, I thought about using paco, despite the warning you have in the README :)

**Comment by gabrielelana** [comment]
@darthdeus sorry for the delay, I didn't expect someone interested at this point of the project :-)

Yep, something to deal with indentation based grammars is the goal of this we, I'll let you know when I have something usable ;-)

**Comment by gabrielelana** [comment]
@darthdeus here you go https://github.com/gabrielelana/paco/blob/25988caa2b431e7a6a1d39660d6d410709bf9d47/examples/08_slim.exs it's just an example, not comparable to what would be to parse the real thing but it's a start.

Your feedback would be much appreciated :smile:, but remember that it's still a work in progress :wink:
